### ISSUE TITLE
Networks can allocated GUID out of pool range

### ISSUE THREAD

**Issue by Mmduh-483** [Mellanox/ib-kubernetes#58]
If the range is `02:00:00:00:00:00:00:00` - `02:00:00:00:00:00:00:FF`, Networks can allocated  GUID like `02:00:00:00:00:FF:00:00`, which is out of pool range.

**Comment by Mmduh-483** [comment]
@adrianchiris @moshe010

**Comment by moshe010** [comment]
is this https://github.com/Mellanox/ib-kubernetes/pull/59 fix the issue?

**Comment by Mmduh-483** [comment]
> is this #59 fix the issue?

No, #59 fixes #45
