### ISSUE TITLE
Example outdated: ib-crd.yaml

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/ib-kubernetes#73]
A recent change in [ib-sriov-cni changed the executable name](https://github.com/Mellanox/ib-sriov-cni/commit/d4049a3c5314fd947e394ca3039896f13ffe80d9). the example should be adapted to the new name.

**Comment by Mmduh-483** [comment]
@moshe010 @adrianchiris Please notice there is a bug now in ib-kubernetes, since it is looking for `network` with type `ib-sriov-cni` but the current existing one is `ib-sriov`
It was caught by the CI job

**Comment by moshe010** [comment]
ok, so can you fix this?

**Comment by Mmduh-483** [comment]
I add a PR

**Comment by adrianchiris** [comment]
Example was updated in commit : https://github.com/Mellanox/ib-kubernetes/commit/c9cfa1350b0a3c9fa462a16b241503ffa55abeb7
