### ISSUE TITLE
Introduce retry mechanism for failed api calls

### ISSUE THREAD

**Issue by DmytroLinkin** [Mellanox/ib-kubernetes#81]
As described in https://github.com/Mellanox/ib-kubernetes/issues/65 comment:

> an API call may fail due to traffic issues or issues with the server (temporary/permanent)

Which can cause infinite update for resource or other unwanted behaviour.

Need to implement retry mechanism for k8s-client & ufm API calls.

**Comment by DmytroLinkin** [comment]
In k8s-client underlying request function already perform retrying.
https://github.com/kubernetes/client-go/blob/master/rest/request.go#L862

For ufm plugin, which use net http client, it's not clear.
Here is corresponding function which do requests:
https://github.com/golang/go/blob/master/src/net/http/client.go#L591

**Comment by adrianchiris** [comment]
> In k8s-client underlying request function already perform retrying.
according to the comment above the code you sent its only if Retry-Response is received.
will that be enough ?

**Comment by DmytroLinkin** [comment]
k8s client by default don't configure backoff (ie. no backoff).
So we fine to do exponential backoff in ib-kubernetes for k8s api calls (and ufm plugin as planned), with leaving a comment about additional time which can appear if somehow client k8s backoff has been configured.
