### ISSUE TITLE
Pod stuck in AddPeriodicUpdate due to race condition with DeletePeriodicUpdate

### ISSUE THREAD

**Issue by DmytroLinkin** [Mellanox/ib-kubernetes#83]
Steps to reproduce:
- create a pod;
- until AddPeriodicUpdate didn't started, delete the pod.

Result:
Messages in the log "Failed to update pod network annotations with error: pod <pod_name> not exist".

**Comment by adrianchiris** [comment]
so the scenario is  ?
- pod created
- watcher registered this event and added pod to addMap
- pod deleted
- add periodic update runs

this seems a viable scenario as long as this pod is not kept in addMap.
maybe log message needs to change adding "pod was possibly deleted"

**Comment by adrianchiris** [comment]
issue solved by recent refactoring done, see PR #81
